{% set name = "openalea.pgljupyter" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
  
source:	
  url: "https://files.pythonhosted.org/packages/9b/87/23f47ad78128a5b15f34a49cfae73cd263749dc72579fbe9a72892035607/pgljupyter-0.2.0-py2.py3-none-any.whl"	
  sha256: f63defc5f265717646836dd8acc9ef2443e67eaf2172b7f6202816ce3f14a7c3	

build:
  number: 0
  script: "{{ PYTHON }} -m pip install pgljupyter-0.2.0-py2.py3-none-any.whl -vv"

requirements:
  host:
    - ipywidgets >=7.5.0
    - jsonschema >=3.2.0
    - jupyterlab >=2.2.0
    - openalea.lpy >=3.5.0
    - openalea.plantgl >=3.5.0
    - pip
    - python
    - toml >=0.10.1
  run:
    - ipywidgets >=7.5.0
    - jsonschema >=3.2.0
    - jupyterlab >=2.2.0
    - openalea.lpy >=3.5.0
    - openalea.plantgl >=3.5.0
    - python
    - toml >=0.10.1

test:
  imports:
    - pgljupyter
    - pgljupyter.nbextension
    - pgljupyter.tests

about:
  home: "https://github.com/jvail/plantgl-jupyter"
  license: Cecill
  license_family: OTHER
  license_file: 
  summary: "PlantGL and L-Py jupyter widget"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - jvail, fredboudon
