{% set name = "openalea.pgljupyter" %}
{% set version = "0.1.21" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install pgljupyter -vv"

requirements:
  host:
    - ipywidgets >=7.5.0
    - jsonschema >=3.2.0
    - jupyterlab >=2.2.0
    - openalea.lpy >=3.4.0
    - openalea.plantgl >=3.4.0
    - pip
    - python
    - toml >=0.10.1
  run:
    - ipywidgets >=7.5.0
    - jsonschema >=3.2.0
    - jupyterlab >=2.2.0
    - openalea.lpy >=3.4.0
    - openalea.plantgl >=3.4.0
    - python
    - toml >=0.10.1

test:
  imports:
    - pgljupyter
    - pgljupyter.nbextension
    - pgljupyter.tests

about:
  home: "https://github.com/jvail/plantgl-jupyter"
  license: Cecill
  license_family: OTHER
  license_file: 
  summary: "PlantGL and L-Py jupyter widget"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - jvail, fredboudon
