{% set name = "pgljupyter" %}
{% set version = "0.1.21" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 778437413679659104b123c16f1ec5e8ceb7554a9a0fbf962d1b73048ac523fe

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - ipywidgets >=7.5.0
    - jsonschema >=3.2.0
    - jupyterlab >=2.2.0
    - openalea.lpy >=3.4.0
    - openalea.plantgl >=3.4.0
    - pip
    - python
    - toml >=0.10.1
  run:
    - ipywidgets >=7.5.0
    - jsonschema >=3.2.0
    - jupyterlab >=2.2.0
    - openalea.lpy >=3.4.0
    - openalea.plantgl >=3.4.0
    - python
    - toml >=0.10.1

test:
  imports:
    - pgljupyter
    - pgljupyter.nbextension
    - pgljupyter.tests

about:
  home: "https://github.com/jvail/plantgl-jupyter"
  license: Cecill
  license_family: OTHER
  license_file: 
  summary: "PlantGL and L-Py jupyter widget"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - jvail, fredboudon
